"""Regenerate evolve_charts/scope_catalog.py from Evolve's frame bucketing source.

Usage (from the repository root):

    python tools/sync_categories.py [path/to/evolve/crates/evolve-frame-bucketing/src/lib.rs]

The Rust source is the single source of truth for which GPU scope (render pass) belongs to which
`WorkloadCategory`, and for the names Evolve shows for them. It also lists the scopes Evolve's pass
bucketing leaves uncategorized (copies, clears, the user interface, ...), which the tool doesn't list as
passes.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = REPO_ROOT.parent / "evolve/crates/evolve-frame-bucketing/src/lib.rs"
OUTPUT = REPO_ROOT / "evolve_charts/scope_catalog.py"

ARM = re.compile(r"Self::(\w+) => vec!\[(.*?)\n\s*\],", re.DOTALL)
NAME = re.compile(r'Self::(\w+) => "([^"]*)",')
TOKEN = re.compile(r'^\s*//.*$|get_or_intern_static\(\s*"(?P<name>[^"]+)"\s*\)', re.MULTILINE)


def _impl(source: str, category: str) -> str:
    start = source.index(f"impl Category for {category}")
    return source[start : source.index("fn translated(self)", start)]


def _lists(body: str) -> dict[str, list[str]]:
    lists = body[: body.index("fn name(self)")]
    return {
        arm.group(1): [token.group("name") for token in TOKEN.finditer(arm.group(2)) if token.group("name")]
        for arm in ARM.finditer(lists)
    }


def _names(body: str) -> dict[str, str]:
    names = body[body.index("fn name(self)") :]
    return {variant: name for variant, name in NAME.findall(names) if name}


def parse(source: str) -> tuple[dict, dict, list[str]]:
    workloads_body = _impl(source, "WorkloadCategory")
    workloads: dict[str, list[str]] = {}
    for workload, scopes in _lists(workloads_body).items():
        for scope in scopes:
            if workload not in workloads.setdefault(scope, []):
                workloads[scope].append(workload)

    uncategorized = _lists(_impl(source, "BucketPassCategory")).get("Uncategorized", [])
    return workloads, _names(workloads_body), uncategorized


def main() -> None:
    source_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SOURCE
    workloads, workload_names, uncategorized = parse(source_path.read_text(encoding="utf-8"))

    lines = [
        "# Generated by tools/sync_categories.py from",
        "# evolve/crates/evolve-frame-bucketing/src/lib.rs. Do not edit by hand.",
        "",
        "# scope name -> WorkloadCategory variants (Evolve lists a handful of scopes in two)",
        "WORKLOADS = {",
        *(f"    {scope!r}: {names!r}," for scope, names in workloads.items()),
        "}",
        "",
        "# variant -> the name Evolve shows",
        "WORKLOAD_NAMES = {",
        *(f"    {variant!r}: {name!r}," for variant, name in workload_names.items()),
        "}",
        "",
        "# Scopes Evolve's pass bucketing (BucketPassCategory) leaves uncategorized",
        "UNCATEGORIZED_PASSES = {",
        *(f"    {scope!r}," for scope in dict.fromkeys(uncategorized)),
        "}",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(workloads)} scope names to {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
